config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sessions/new'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/instruction', to: 'static_pages#instruction'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'class_sessions/user_class'
  get 'class_sessions/user_group'
  resources :users 
  resources :evaluations
  resources :class_sessions do
    collection do
      post 'add_user_to_class'
      post 'add_user_to_group'
    end
  end
  resources :projects do
    collection do
      post 'generate_evaluations'
    end
  end
  resources :groups
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :project
  belongs_to :evaluator, :class_name => "User", :foreign_key => :evaluator_id
  belongs_to :evaluatee, :class_name => "User", :foreign_key => :evaluatee_id
  after_initialize :default_vals
  validates :evaluator_id, presence: true, numericality: {greater_than:0}
  validates :evaluatee_id, presence: true, numericality: {greater_than:0}
  validates :score, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
  validates :assessment, presence: true
  validates :group_id, presence: true, numericality: {greater_than:0}
  validates :project_id, presence: true, numericality: {greater_than:0}

  def default_vals
    self.submitted = false if self.submitted.nil?
    self.score = 0 if self.score.nil?
  end

  def in_time_window?
    if access_closes and access_opens then
      return Time.zone.now.between?(access_opens, access_closes)
    end
    return true
  end
  
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :show, :destroy]
  # Shows all evaluations
  # 
  #
  def index   
    @evaluations = Evaluation.all
    @user = User.find(current_user.id)
  end

  # Shows one evaluation for a student
  #
  #
  def show
    @evaluation = Evaluation.find(params[:id])
  end

  # Gets a form for editing a evaluation for a student
  # 
  #
  def edit
    @evaluation = Evaluation.find(params[:id])
  end

  def update
    @evaluation = Evaluation.find(params[:id])
    if @evaluation.update(evaluation_params)
      @evaluation.submitted = true
      @evaluation.save
     flash[:success] = "Evaluation submitted"
     redirect_to evaluations_path
    else
      render 'edit'
    end
  end
  # Gets a form for a new evaluation for a student
  # 
  #
  def new
    @evaluation = Evaluation.new
  end

  # Deletes an evaluation
  # 
  #
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  def evaluation_params
    params.require(:evaluation).permit(:evaluator_id, :evaluatee_id, :submitted)
  end


  def evaluation_params
    params.require(:evaluation).permit(:evaluation_id, :evaluatee_id, :score, :assessment,
                                 :project, :group, :submitted)
  end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_class-group-collapsible.erb
<button type="button" class="collapsible">
<%completeStyle = "incomplete"%>
	<% if class_session.groups_complete? then completeStyle = "complete" end%>
	<%= class_session.name + "\t"=%>  
	<%if class_session.has_evaluations? %>
	<span class="<%=completeStyle=%>"><%=class_session.number_complete_groups.to_s =%></span>
	<%= "/" + class_session.number_groups.to_s =%>
	<% end %>
	<%= link_to "page", class_session, class: "btn btn-lg btn-primary btn-admin btn-in-btn" %> 

	</button>
	<div class="content">
	  	<ul class="groupProjects">
			<% class_session.get_groups().each do |group| %> 
				<%= render "evaluations/group-projects-collapsible", :group => group =%>
			<% end %>
		</ul>
	</div>

app/views/evaluations/_display-evaluation.erb
<% evaluator = User.find evaluation.evaluator_id %>
<td><%= evaluator.first_name %> <%= evaluator.last_name %></td>

<% evaluatee = User.find evaluation.evaluatee_id %>
<td><%= evaluatee.first_name %> <%= evaluatee.last_name %></td>

<% project = Project.find evaluation.project_id %>
<td><%= project.name %></td>

<% group = Group.find evaluation.group_id %>
<td><%= group.name %></td>

<td>

  <% if evaluation.submitted %>
    <%= link_to 'Show', evaluation %>
  <% else %>
    <% if evaluation.in_time_window? %>
        <%if @user.id == evaluation.evaluator_id%>
          <%= link_to 'Complete', edit_evaluation_path(evaluation), :class => "incomplete" %>
        <%else%>
          <%= "pending..." =%>
        <%end%>
     <%else%>
      <%= "Window has not opened" =%>
     <%end%>

  <%end%>

</td>

app/views/evaluations/_group-projects-collapsible.erb
<button type="button" class="collapsible">
<%completeStyle = "incomplete"%>
	<% if group.projects_complete? then completeStyle = "complete" end%>
	<%= group.name + "\t"=%>  
	<%if group.has_evaluations? %>
	<span class="<%=completeStyle=%>">
	<%=group.number_complete_projects.to_s =%></span><%= "/" + group.number_projects.to_s =%>
	<% end %>
	<%= link_to "page", group, class: "btn btn-lg btn-primary btn-admin btn-in-btn" %> 

</button>
	<div class="content">
	  	<ul class="groupProjects">
			<% group.get_projects.each do |project| %> 
				<%= render "evaluations/project-evaluations-collapsible", :project => project =%>
			<% end %>
		</ul>
	</div>

app/views/evaluations/_professor-evaluations.erb
  <%professorClasses = @user.getClasses%>
  <% professorClasses.each do |class_session| %>
    <tr>
    <%= render "evaluations/class-group-collapsible", :class_session => class_session =%>
    </tr>
   <% end %>

app/views/evaluations/_project-evaluations-collapsible.erb
<button type="button" class="collapsible">
	<%completeStyle = "incomplete"%>
	<% if project.complete? then completeStyle = "complete" end%>
	<%= project.name + "\t"=%> 
	<%if project.number_evaluations > 0 %> 
	<span class="<%=completeStyle=%>"><%=project.number_complete_evaluations.to_s =%></span>
	<%= "/" + project.number_evaluations.to_s =%> 
	<%end%>
	<%= link_to "page", project, class: "btn btn-lg btn-primary btn-admin btn-in-btn" %> 

	</button>
<div class="content">
<table class="table">
  <tr>
    <th>Evaluator</th>
    <th>Evaluatee</th>
    <th>Project</th>
    <th>Group</th>
    <th>Evaluation</th>
  </tr>
	  	<ul class="projectEvaluations">
			<% project.get_evaluations.each do |evaluation| %> 
				<tr>
				<%= render "evaluations/display-evaluation", :evaluation => evaluation =%>
				</tr>
			<% end %>
		</ul>
		</table>
	</div>

app/views/evaluations/_student-evaluations.erb
  
<%studentEvaluations = @evaluations.where(evaluator_id: current_user.id)%>
<table class="table">
  <tr>
    <th>Evaluator</th>
    <th>Evaluatee</th>
    <th>Project</th>
    <th>Group</th>
    <th>Evaluation</th>
  </tr>
<% studentEvaluations.each do |evaluation| %>
    <tr>
    <div class="evaluation">
      <%= render "evaluations/display-evaluation", :evaluation => evaluation =%>
    </div>
    </tr>
  <% end %>
</table>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= form_with(model: @evaluation, local: true) do |f| %>
    <%if @evaluation%>
    <%= render 'shared/error_messages', :errors => @evaluation.errors %>
    <%end%>
    <%= f.label :score %>
    <%= f.text_field :score, class: 'form-control' %>
  
    <%= f.label :assessment %>
    <%= f.text_field :assessment, class: 'form-control' %>
  
    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<h1>Evaluations</h1>

  
  <%if @user.student? %>
    <%= render 'student-evaluations' %>
  <%elsif @user.admin? %>
    <%= render 'professor-evaluations' =%>
  <% end %>

<%= render 'shared/collapsible_script' =%>

app/views/evaluations/new.html.erb
<h1> Generate Evaluations for Project </h1>
<hr/>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3 form">
      <%= form_for("Project", url: generate_evaluations_projects_url) do |f| %> 
        
        <%= f.label "Evaluation window opens" %>
        <%= f.datetime_select  :evaluation_window_starts %>
        
        <%= f.label "Evaluation window closes" %>
        <%= f.datetime_select  :evaluation_window_ends_ %>
        
        <%= f.hidden_field :eval_project, value: params[:project] %>
        <%= f.submit "Submit" %>
      <% end %>
    </div>
  </div> 

app/views/evaluations/show.html.erb
<h1> Peer Evaluation </h1>
<div class="evaluation_display">
    <h2> Evaluator: </h2>
    <% evaluator = User.find_by id: @evaluation.evaluator_id %>
    <p class="displayed"><%= evaluator.first_name %> <%= evaluator.last_name %></p>
    <br />
    <h2> Evaluatee: </h2>
    <% evaluatee = User.find_by id: @evaluation.evaluatee_id %>
    <p><%= evaluatee.first_name %> <%= evaluatee.last_name %></p>
    <br />
    
    <h2> Score: </h2>
    <p><%= @evaluation.score %></p>
    <br />

    <h2> Assessment: </h2>
    <p><%= @evaluation.assessment %></p>
    <br />
</div>