config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sessions/new'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/instruction', to: 'static_pages#instruction'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'class_sessions/user_class'
  get 'class_sessions/user_group'
  resources :users 
  resources :evaluations
  resources :class_sessions do
    collection do
      post 'add_user_to_class'
      post 'add_user_to_group'
    end
  end
  resources :projects do
    collection do
      post 'generate_evaluations'
    end
  end
  resources :groups
end

app/models/class_session.rb
class ClassSession < ApplicationRecord
  has_many :groups
  has_many :user_class_x_refs, :inverse_of => :class_session
  has_many :users, :through => :user_class_x_refs
  has_many :projects

  validates :name, presence: {message: 'Class name needed'}
  
  def get_groups
    return Group.where(class_session_id: self.id)
  end

  def groups_complete?
    return number_complete_groups == number_groups
  end

  def number_complete_groups
    groups = get_groups
    completed_groups= 0;
    groups.each do |group|
      if group.projects_complete? then
        completed_groups += 1
      end
    end
    return completed_groups
  end

  def number_groups
    return get_groups.count
  end

  def has_evaluations?
    return get_groups.any? {|group| group.has_evaluations?}
  end
end

app/controllers/class_sessions_controller.rb
class ClassSessionsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :show, :destroy]
  def index
    @class_sessions = ClassSession.paginate(page: params[:page])
  end
  
  def show
    @class_session = ClassSession.find(params[:id])
    @user = current_user
  end

  def new
    @class_session = ClassSession.new
    xref = UserClassXRef.new(:user_id => current_user.id, :class_session_id => @class_session.id)
    xref.save
  end

  def create
     @class_session = ClassSession.new(class_session_params)
     if @class_session.save
       flash[:success] = "Successfully created your class!"
       xref = UserClassXRef.new(:user_id => current_user.id, :class_session_id => @class_session.id)
       xref.save
       redirect_to "/"
     else
       render 'new'
     end
   end

   def edit
     @user = User.find(params[:id])
   end

   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
     else
       render 'edit'
     end
   end
 
   def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
   end


   def add_user_to_class
    xref = UserClassXRef.new()
    xref.class_session_id = params[:Class_session][:class_session_id]
    users = User.where(:first_name => params[:Class_session][:first_name], :last_name => params[:Class_session][:last_name])
    byebug
    user_id = users.first.id
    xref.user_id = user_id
    if xref.save
      flash[:success] = "Student added to class"
      redirect_to "/"
     else
      flash[:warning] = "Student not successfully added. There may not be a student with that name. Check the users page to be sure."
     end
   end

   def add_user_to_group
    xref = UserGroupXRef.new()
    groups = Group.where(:name => params[:Class_session][:name])
    group_id = groups.first.id
    xref.group_id = user_class_params[group_id]
    users = User.where(:first_name => user_class_params[:Class_session][:first_name], :last_name => user_class_params[:Class_session][:last_name])
    user_id = users.first.id
    xref.user_id = user_id
    if xref.save
      flash[:success] = "Student added to group"
      redirect_to "/"
     else
      flash[:warning] = "Student not successfully added. There may not be a student or group with that name."
     end
   end
   
   private
   def class_session_params
     params.require(:class_session).permit(:name)
   end

   def user_class_params
    params.permit(:first_name, :last_name, :class_session_id)
   end

  def user_group_params
    params.permit(:first_name, :last_name, :group_name)
  end
  
end

app/helpers/class_sessions_helper.rb
module ClassSessionsHelper

    # def randomize_groups
    #     @class_session = ClassSession.find(params[:id])
    
    #     user_class_xrefs = UserClassXRef.where(class_session_id: @class_session.id)
    #     num_students = user_class_xrefs.count
    #     groups = Group.where(class_session_id: @class_session.id)
    #     num_groups = @class_session.number_groups
    
    #     if (num_groups == 0) then
    #       flash[:warn] = "Add some groups first!"
    #     elsif (num_students == 0) then
    #       flash[:warn] = "Add some groups first!"
    #     else
    #       max_students_per_group = (num_students / num_groups).ceil()
    
    #       user_class_xrefs.each do |xref|
    #         student = User.find(xref.user_id)
    
    #         loop do
    #           group = groups.sample
    #           user_group_xrefs = UserGroupXRef.where(group_id: group.id)       
    #         break if (user_group_xrefs.count < max_students_per_group)
    #         end
    
    #         new_user_group_xref = UserGroupXRef.new(group_id: group.id, user_id: xref.user_id)
    #         new_user_group_xref.save
    #       end
    #     end
    
    # end  

end

app/views/class_sessions/_class-form.html.erb
<div class="form">
<%= form_with(model: @class_session, local: true) do |f| %>
  <%# <%= render 'error_messages', object: @class_session %> 
    <%# need error handling%>

  <b>Enter a name for your class...</b><br/>
  <p>Remember: this name should be unique to this section</p>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>


  <%= f.submit button_text, class: "btn btn-primary btn-admin" %>
<% end %>
</div>

app/views/class_sessions/_class_session.html.erb
<br>
<li>
<div >
      <h3> <%= link_to class_session.name, class_session %> </h3>
           
      <% if current_user.admin?%>
        <p class="center">
         <%= link_to "DELETE", class_session, method: :delete,
                                            data: { confirm: "You sure?" } %>

         </p>
      <% end %>
  </div>
</li>

app/views/class_sessions/_error_messages.html.erb
<% if @class_session.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@class_session.errors.count, "error") %>.
    </div>
    <ul>
    <% @class_session.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/class_sessions/add_user_to_class.html.erb
<h1> Add Student to Class </h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 form">
      <%= form_with url: "/class_session/add_user_to_class", method: :get do |form| %> 
        
        <%= f.label :first_name %>
        <%= f.text_field  :first_name, class: 'form-control' %>
    
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %> 
        
        <%= f.hidden_field :class_session_id, value: params[:class_session_id] %>
        <%= f.submit "Add Student", class: "btn btn-primary btn-admin"  %>
      <% end %>
    </div>
  </div> 

app/views/class_sessions/add_user_to_group.html.erb
<h1> Add Student to Group </h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 form">
      <%= form_with url: "/class_session/add_user_to_group", method: :get do |form| %> 
        
        <%= f.label :first_name %>
        <%= f.text_field  :first_name, class: 'form-control' %>
    
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %> 
        
        <%= f.label :group_name %>
        <%= f.text_field :group_name, class: 'form-control' %> 
        <%= f.submit "Add Student", class: "btn btn-primary btn-admin"  %>
      <% end %>
    </div>
  </div> 

app/views/class_sessions/edit.html.erb
<% provide(:title, "Edit class") %>
<h1>Update your class name</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'class-form', :button_text => "Save Changes" %>
  </div>
</div>

app/views/class_sessions/index.html.erb
<h1>All Classes</h1>

<%= will_paginate %>

<ul>
  <%= render @class_sessions %>
</ul>

<%= will_paginate %>

app/views/class_sessions/new.html.erb
<% provide(:title, 'New Class') %>
<h1>Add Class</h1>

  <%= link_to "Back to Profile", current_user %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= render 'class-form', :button_text => "Create Class" %>
  </div>
</div>

app/views/class_sessions/show.html.erb
<% provide(:title, @class_session.name) %>
<h1><%= @class_session.name %></h1>

<div class="class display">
  <h2>Professor 
  <% user_class_x_refs = UserClassXRef.where(class_session_id: @class_session.id) %>
    <% user_class_x_refs.each do |xref| %>
    <%user = User.find(xref.user_id)%>
    <% if user.admin? %>
      <%= user.first_name + " " + user.last_name %>
      </h2>
    <% end %>
  <% end %>

    <h2>Projects</h2>
  <% projects = Project.where(class_session_id: @class_session.id) %>
  <ul>
  <% projects.each do |project| %>
    <li> <%= project.name =%> </li>
  <% end %>
  </ul>
  <% if @user.admin? %>
    <h3>Project Controls</h3>
    <div class = "center">
      <%= link_to "Add Project", {:controller => "projects", :action => "new", :class_session_id => @class_session.id }, class: "btn btn-lg btn-primary btn-admin" %> 
      <%= link_to "Edit Project", "/projects/edit", class: "btn btn-lg btn-primary btn-admin" %> 
    </div>
  <% end%>
  

  <h2>Groups</h2>
  <% groups = Group.where(class_session_id: @class_session.id) %>
  <% groups.each do |group| %>
    <button type="button" class="collapsible"><%= group.name =%><%= link_to "page", group, class: "btn btn-lg btn-primary btn-admin btn-in-btn" %></button>
    <div class="content">
      <% members = group.students %>
      <ul>
        <% members.each do |member| %>
          <li> <%= member.first_name =%> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user.admin? %>
    <h3>Group Controls</h3>
    <div class = "center">
      <%= link_to "Add Group", {:controller => "groups", :action => "new", :class_session_id => @class_session.id }, class: "btn btn-lg btn-primary btn-admin" %>
      <%= link_to "Edit Group", "/groups/edit", class: "btn btn-lg btn-primary btn-admin" %>
    </div>
  <% end%>

  <h2>Students</h2>
  <% xrefs = UserClassXRef.where(class_session_id: @class_session.id) %>
  <% xrefs.each do |xref| %>
    <%user = User.find(xref.user_id)%>
    <% if !user.admin? %>
      <%= render user%>
    <% end %>
  <% end %>
  <% if current_user.admin? %>
    <h3>Student Controls</h3>
    <div class="center">
      <%= link_to "Add Student to Class", {:action => "user_class", :class_session_id => @class_session.id }, class: "btn btn-lg btn-primary btn-admin" %> 
      <%= link_to "Add Student to Group", {:action => "user_group"}, class: "btn btn-lg btn-primary btn-admin" %> 
    </div>
  <% end%>

  
</div>

<%= render 'shared/collapsible_script' %> 

app/views/class_sessions/user_class.html.erb
<h1> Add Student to Class </h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 form">
      <%= form_for("Class_session", url: add_user_to_class_class_sessions_url) do |f| %> 
        
        <%= f.label :first_name %>
        <%= f.text_field  :first_name, class: 'form-control' %>
    
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %> 
        
        <%= f.hidden_field :class_session_id, value: params[:class_session_id] %>
        <%= f.submit "Add Student", class: "btn btn-primary btn-admin"  %>
      <% end %>
    </div>
  </div> 

app/views/class_sessions/user_group.html.erb
<h1> Add Student to Group </h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 form">
      <%= form_for("Class_session", url: add_user_to_group_class_sessions_url) do |f| %> 
        
        <%= f.label :first_name %>
        <%= f.text_field  :first_name, class: 'form-control' %>
    
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %> 
        
        <%= f.label :group_name %>
        <%= f.text_field :group_name, class: 'form-control' %> 
        <%= f.submit "Add Student", class: "btn btn-primary btn-admin"  %>
      <% end %>
    </div>
  </div> 