config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'sessions/new'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/instruction', to: 'static_pages#instruction'
  get 'users/new'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'class_sessions/user_class'
  get 'class_sessions/user_group'
  resources :users 
  resources :evaluations
  resources :class_sessions do
    collection do
      post 'add_user_to_class'
      post 'add_user_to_group'
    end
  end
  resources :projects do
    collection do
      post 'generate_evaluations'
    end
  end
  resources :groups
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
   The peer evaluation tool designed by Team Byte Me
</small>
<nav>
  <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <% if current_user.student?%>
    <header class="navbar navbar-fixed-top navbar-inverse nav-student">
  <% end %>
  <% if current_user.admin?%>
    <<header class="navbar navbar-fixed-top navbar-inverse nav-admin">
  <% end %>
<% else %>
  <header class="navbar navbar-fixed-top navbar-inverse">
<% end %>
  <div class="container">
    <% if logged_in? %>
      <% if current_user.student?%>
        <%= link_to "Evaluation Tool: Student View", root_path, id: "logo" %>
      <% end %>
      <% if current_user.admin?%>
        <%= link_to "Evaluation Tool: Professor View", root_path, id: "logo" %>
      <% end %>
    <% else %>
      <%= link_to "Evaluation Tool", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
    <% end %>

      <nav>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Classes", class_sessions_path %></li>
          <li><%= link_to "Users", users_path %></li>

            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <% if current_user.student?%>
              <ul class="dropdown-menu nav-student" role="menu">
            <% end %>
            <% if current_user.admin?%>
              <ul class="dropdown-menu nav-admin" role="menu">
            <% end %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
   </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
   </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Peer Evaluation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <link href='https://fonts.googleapis.com/css?family=Work Sans' rel='stylesheet'>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>